name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Скачать проект
      - name: Checkout code
        uses: actions/checkout@v4

      # Установить Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Установить зависимости
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Проверка файлов
      - name: Show backend files
        run: |
          ls backend

      # Запуск тестов
      - name: Run tests
        run: |
          cd backend
          pytest
